server:
  port: 8000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /**

    # 设置虚拟地址映射，将本地地址映射成服务器静态资源地址
  web:
    resources:
      static-locations: file:E:\project\java\src\main\resources\static





